FROM debian:trixie-slim as build-env

ARG DEBIAN_FRONTEND=noninteractive

RUN apt update && apt upgrade -y \
  # install tools
  && apt install -y --no-install-recommends unzip curl \
  # install spring dependencies
  && apt install -y --no-install-recommends openjdk-21-jdk maven \
  # make image smaller
  && rm -rf "/var/lib/apt/lists/*" \
  && rm -rf /var/cache/apt/archives

ARG USER=spring
RUN useradd --create-home --shell /bin/bash $USER
ARG HOME="/home/$USER"
WORKDIR $HOME
USER $USER

RUN java --version
RUN mvn --version

# https://github.com/spring-io/initializr
RUN curl "https://start.spring.io/starter.zip?type=maven-project&language=java&bootVersion=4.0.1&baseDir=demo&groupId=com.example&artifactId=demo&name=demo&description=Demo%20project%20for%20Spring%20Boot&packageName=com.example.demo&packaging=jar&javaVersion=21&dependencies=web" --output springdemo.zip \
  && unzip springdemo.zip

WORKDIR "/home/$USER/demo"

COPY DemoApplication.java ./src/main/java/com/example/demo/DemoApplication.java

EXPOSE 8888

CMD [ "mvn", "spring-boot:run", "-Dspring-boot.run.jvmArguments='-Dserver.port=8888'"]

HEALTHCHECK CMD curl -f "http://localhost:8888/hello?name=health&" || exit 1
